import "./globals.css";

export const metadata = {
  title: "Next-Country",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-stone-100">{children}</body>
    </html>
  );
}
